flowchart LR
  A["Client/main.cpp<br/>wWinMain"] --> B["CEngine::GetInst()"]
  B --> C["CEngine::Init"]

  click A "index.html#file=Client/main.cpp&line=19" "wWinMain"
  click B "index.html#file=Engine/Engine.h&line=43" "GetInst"
  click C "index.html#file=Engine/Engine.cpp&line=30" "Init"
