flowchart LR

  A[Client/main.cpp<br/>wWinMain] --> B[CEngine::GetInst()]
  B --> C[CEngine::Init(...)]

  click A "index.html#file=Client/main.cpp&line=19" "wWinMain (Client/main.cpp)"
  click B "index.html#file=Engine/Engine.h&line=43" "CEngine::GetInst (Engine.h)"
  click C "index.html#file=Engine/Engine.cpp&line=30" "CEngine::Init (Engine.cpp)"


  %% ======================
  %% Client Entry
  %% ======================
  ClientMain[Client/main.cpp<br/>wWinMain]

  %% ======================
  %% Core Engine
  %% ======================
  Engine[GameEngine/Engine]
  Device[Device]
  Timer[Timer]

  %% ======================
  %% World / Object
  %% ======================
  WorldMgr[WorldManager]
  World[World]
  GameObject[GameObject]
  Component[Component]
  SceneComponent[SceneComponent]
  MeshComponent[MeshComponent]

  %% ======================
  %% Asset System
  %% ======================
  AssetMgr[AssetManager]
  PathMgr[PathManager]

  ShaderMgr[ShaderManager]
  Shader[Shader]
  GraphicShader[GraphicShader]
  ComputeShader[ComputeShader]

  MeshMgr[MeshManager]
  Mesh[Mesh]

  %% ======================
  %% Flow
  %% ======================
  ClientMain --> Engine
  Engine --> Device
  Engine --> Timer
  Engine --> WorldMgr
  Engine --> AssetMgr

  WorldMgr --> World
  World --> GameObject
  GameObject --> Component
  Component --> SceneComponent
  SceneComponent --> MeshComponent

  AssetMgr --> PathMgr
  AssetMgr --> ShaderMgr
  AssetMgr --> MeshMgr

  ShaderMgr --> Shader
  Shader --> GraphicShader
  Shader --> ComputeShader

  MeshMgr --> Mesh
